feat: [NPM] num ACL rules for v2 & update existing metrics
Azure/azure-container-networking pull request #1223
Opened 2022-02-04 23:35 UTC by huntergregory

The following updates with UTs:
- Adds ACL rule metrics to v2
  - for windows: add the number of ingress and egress rules
  - for Linux: same but add 1 if any ACLs are ingress and 1 if any are egress (for the jumps to the policy ingress/egress chains)
- Moves v2 metric updates in ResetIPSets() from OS to the generic ipsetmanager (and also clears all caches in this function)
- in v1 and v2, moves ipset/acl rule exec times to be the exact time of the OS call (and no other code before/after)
- Updates a tiny flaw in ipsm.go if there were a flush success and destroy failure while resetting ipsets

2022-02-09 01:42 UTC, vakalapa requested changes

2022-02-09 01:42 UTC, vakalapa commented on npm/pkg/dataplane/policies/policy_windows.go
> +	numRules := 0
Even in Windows we have the extra block rule we should calculate. So the linux function is actually good for both OS.

2022-02-09 01:42 UTC, vakalapa commented on npm/pkg/dataplane/policies/policymanager.go
> +	for i := 0; i < policy.numACLRulesProducedInKernel(); i++ {
instead of having these loops here, can we have a func metrics.IncNumAclsByNum() which takes in an int and loops inside ?

2022-02-09 01:42 UTC, vakalapa commented on npm/pkg/dataplane/policies/policymanager.go
> +	for i := 0; i < policy.numACLRulesProducedInKernel(); i++ {
Same as above can we have a metrics.DecNumAclByNum ?

2022-02-09 23:54 UTC, rbtr commented on npm/pkg/dataplane/policies/policy.go
> +	for _, item := range netPol.ACLs {
agree, implementing `String()` does feel a little Java to me 🙂

2022-02-10 00:44 UTC, vakalapa commented on npm/pkg/dataplane/policies/policy.go
> +	for _, item := range netPol.ACLs {
Discussed this internally and team decided to change this func to PrettyPrint() and will be tackled in a separate PR

2022-02-10 00:48 UTC, vakalapa approved these changes

2022-02-10 04:38 UTC, merged

2022-10-17 21:10 UTC, huntergregory commented on npm/pkg/dataplane/policies/policy.go
> +	for _, item := range netPol.ACLs {
resolved in #1235