npm: enable debug feature parity for v2
Azure/azure-container-networking pull request #1324
Opened 2022-04-07 17:24 UTC by matmerr

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2022-04-13 17:50 UTC, rbtr commented
@vakalapa you might want to update the [reviewers team](https://github.com/orgs/Azure/teams/acn-npm-reviewers) 🙂

2022-04-13 23:50 UTC, rbtr commented on npm/util/ioutil/restore.go
> +		msg := fmt.Sprintf("on try number %d, failed to run command [%s]. Rerunning with %s file. Had error [%s].Used file:%s", creator.tryCount, commandString, sameNew, err.Error(), fileString)
logs shouldn't be multiline. one log per line pls

2022-04-20 16:40 UTC, matmerr commented on npm/cmd/gettuples.go
> +				if config.Toggles.EnableV2NPM {
redundant block as below

2022-04-20 18:42 UTC, matmerr commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +	log.Printf("matched cidr")
remove

2022-04-20 18:42 UTC, matmerr commented on npm/pkg/dataplane/debug/trafficanalyzerv2.go
> +package debug
remove

2022-04-20 18:43 UTC, matmerr commented on npm/pkg/dataplane/ipsets/ipsetmanager.go
> +func (iMgr *IPSetManager) GetAllIPSets() map[string]string {
add comment what return map key and value are

2022-04-20 18:45 UTC, matmerr commented on npm/npm.go
> +		cachev2.NsMap = npMgr.NamespaceControllerV2.GetCache()
condense into struct declaration

2022-04-20 20:08 UTC, matmerr commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +			log.Printf("matched named ports")
remove

2022-04-20 20:08 UTC, matmerr commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +	log.Printf("matched key label of pod")
remove

2022-04-20 20:08 UTC, matmerr commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +	log.Printf("matched key value label of pod")
remove

2022-04-20 20:22 UTC, vakalapa commented on npm/http/api/api.go
> +	NPMV2CacheAPI      = "/npm/v2/debug/cache"
Not needed, since marshall takes care of this now.

2022-04-20 21:34 UTC, vakalapa requested changes

2022-04-20 21:34 UTC, vakalapa commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +func GetInputType(input string) common.InputType {
move this function to where input type is defined.

2022-04-20 21:34 UTC, vakalapa commented on npm/pkg/dataplane/debug/trafficanalyzer.go
>  				matched = false
redundant remove line

2022-04-20 21:34 UTC, vakalapa commented on npm/pkg/dataplane/debug/trafficanalyzer.go
> +		matched := false
In V2 we have cut down a single rule, into a half match in top level ingress or egress chain and then jump to Netpol specific ingress or egress chain and match the 2nd half of the packet in a given direction, that change is still missing

2022-06-02 18:02 UTC, huntergregory reviewed
converter logic looks good now

2022-06-14 18:58 UTC, merged