Fix CNS logging
Azure/azure-container-networking pull request #1372
Opened 2022-05-10 23:15 UTC by camrynl

**Reason for Change**:

 OrchestratorContext cannot always be unmarshalled due to different orchestrator types, so updating CNS logging to exclude it

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2022-05-10 23:28 UTC, rbtr requested changes
if we want to dump (only some) struct fields, maybe `cns.CreateNetworkContainerRequest` should implement [`fmt.Stringer`](https://pkg.go.dev/fmt#Stringer)?

2022-05-11 18:49 UTC, tamilmani1989 submitted a review, later dismissed
lgtm

2022-05-11 21:14 UTC, rbtr requested changes

2022-05-11 21:14 UTC, rbtr commented on cns/NetworkContainerContract.go
> +	return fmt.Sprintf("[Azure CNS] cns.CreateNetworkContainerRequest "+
this log metadata shouldn't be in the String method, it should only return a string representation of the struct
```suggestion
	return fmt.Sprintf("CreateNetworkContainerRequest"+
```

2022-05-11 21:47 UTC, rbtr approved these changes
thanks for cleaning this up 🚀

2022-05-12 18:22 UTC, rbtr commented
hey @camrynl you are welcome to merge. you should also usually have an "enable auto-merge" button so that you don't have to come back later after the CI and approvals are in 🙂

2022-05-12 18:30 UTC, camrynl commented
@rbtr noted, thanks!

2022-05-12 18:31 UTC, merged