Update Swift pipeline w byo cluster
Azure/azure-container-networking pull request #1475
Opened 2022-07-18 23:35 UTC by camrynl

**Reason for Change**:

Current e2e tests are utilizing an existing cluster. Each PR waits for the cluster to be available before running tests.
Adding byo cluster feature to pipeline so each PR can run tests in parallel using its own cluster.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2022-07-18 23:37 UTC, camrynl commented
PR still in progress. Can't convert to draft since I'm testing the pipeline. I'll notify when to review, ty :)

2022-07-27 16:48 UTC, rbtr requested changes

2022-07-27 16:48 UTC, rbtr commented on .pipelines/singletenancy/aks-swift/e2e-step-template.yaml
> +      azureSubscription: "Azure Container Networking - Test"
there is a pipeline var for this Sub, we should use it

2022-07-27 16:48 UTC, rbtr commented on cns/azure-cns.yaml
> +          image: mcr.microsoft.com/containernetworking/azure-cns:v1.4.29
Can you revert this? I think this manifest is used by partners, and is unrelated to this change anyway

2022-07-27 16:48 UTC, rbtr commented
You can also remove this line https://github.com/Azure/azure-container-networking/blob/637d5affe966f2aadf0240e64afc0cc34e481696/.pipelines/singletenancy/aks-swift/e2e-job-template.yaml#L9 which currently prevents this test job from running in parallel 🙂

2022-07-27 17:59 UTC, rbtr approved these changes
🚀🚀

2022-07-27 21:12 UTC, merged