fixed not allocating loggerCfg in main
Azure/azure-container-networking pull request #1477
Opened 2022-07-19 00:17 UTC by nddq

As described in title.

2022-07-19 01:06 UTC, rbtr requested changes

2022-07-19 01:06 UTC, rbtr commented on azure-ipam/main.go
> +	loggerCfg := &logger.Config{}
maybe inline setting the opts from right below?
```suggestion
	loggerCfg := &logger.Config{
		Level: 		  "debug",
		OutputPaths: 	  "stdout",
		ErrorOutputPaths: "stderr"
	}
```

2022-07-19 18:13 UTC, rbtr approved these changes

2022-07-20 20:09 UTC, tamilmani1989 approved these changes

2022-07-21 16:15 UTC, merged