feat: Add SNAT bridge to Native, decouple SNAT bridge
Azure/azure-container-networking pull request #1506
Opened 2022-08-03 16:48 UTC by QxBytes

**Reason for Change**:
Adds SNAT bridge functionality to the native datapath and decouples the OVS-specific SNAT bridge code from the more general SNAT bridge code.

**Issue Fixed**:
N/A

**Requirements**:

- [X] uses [conventional commit messages](https://www.conventionalcommits.org/)
- [X] includes documentation
- [X] adds unit tests

**Notes**:
- The network package was `gofumpt` so there may be style fixes in the following files not directly related to this feature (See commit "Go fumpt entire network package" for those files). 
- Some code was moved around/renamed/re-used. In particular, snat_linux.go (and most other files) consists of already-existing code that was re-used.
- The idea is that OVS and Native have their own versions of SNAT/snat route, which call a common set of behaviors in endpoint_snatroute_linux.go, which uses the client to call something in snat_linux.go

2022-08-03 19:31 UTC, rbtr commented
could you pull the gofumpt of the whole package out into a separate PR? happy to merge that one first

2022-08-04 06:18 UTC, tamilmani1989 requested changes

2022-08-06 03:41 UTC, tamilmani1989 requested changes
i see you updates ovs snat as well.. did you test snat bridge scenarios work in ovs case?

2022-08-09 21:56 UTC, tamilmani1989 requested changes

2022-08-09 21:56 UTC, tamilmani1989 commented on cni/azure-windows-multitenancy-transparent-vlan.conflist
> +            "mode": "transparentVlan",
transparent-vlan

2022-08-09 21:56 UTC, tamilmani1989 commented on network/endpoint_snatroute_linux.go
> +	if ncToHost {
snatClient.AllowInboundNCToHost()

2022-08-09 21:56 UTC, tamilmani1989 commented on network/endpoint_snatroute_linux.go
> +	return errors.Wrap(snatClient.MoveSnatEndpointToContainerNS(netnsPath, nsID), "failed to move snat endpoint to container ns")
change everything to same format

2022-08-09 21:56 UTC, tamilmani1989 commented on network/network.go
> +	opModeTransparentVlan = "transparentVlan"
transparent-vlan

2022-08-09 21:56 UTC, tamilmani1989 commented on network/ovs_endpoint_snatroute_linux.go
> +		// Add route for 169.254.169.54 in host via azure0, otherwise it will route via snat bridge
169.254.169.**2**54

2022-08-09 21:56 UTC, tamilmani1989 commented on network/transparent_vlan_endpointclient_linux.go
> +				log.Errorf("deleting vlan veth failed on addendpoint failure")
move to defer

2022-08-09 21:56 UTC, tamilmani1989 commented on network/transparent_vlan_endpointclient_linux.go
> +	if err = client.ConfigureSnatContainerInterface(); err != nil {
move this to end of function

2022-08-09 21:56 UTC, tamilmani1989 commented on network/transparent_vlan_endpointclient_linux.go
> +	}
move to end of function

2022-08-10 20:49 UTC, tamilmani1989 approved these changes

2022-08-10 20:50 UTC, merged