upgrade goldpinger version and increase ping/check timeout
Azure/azure-container-networking pull request #1810
Opened 2023-02-17 19:18 UTC by ZetaoZhuang

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2023-02-21 17:50 UTC, timraymond submitted a review, later dismissed
Changes seem reasonable to me 👍

2023-02-22 18:09 UTC, timraymond requested changes
Small request: If these configs now allow units, it would be more obvious to readers to use seconds instead of making them do the math.

2023-02-22 18:09 UTC, timraymond commented on test/integration/manifests/goldpinger/daemonset.yaml
> +              value: "10000ms"
```suggestion
              value: "10s"
```

2023-02-22 18:09 UTC, timraymond commented on test/integration/manifests/goldpinger/daemonset.yaml
> +              value: "20000ms"
```suggestion
              value: "20s"
```

2023-02-22 18:09 UTC, timraymond commented on test/integration/manifests/goldpinger/daemonset.yaml
> +              value: "20000ms"
```suggestion
              value: "20s"
```

2023-02-22 22:29 UTC, estebancams approved these changes

2023-02-23 01:20 UTC, timraymond approved these changes

2023-02-23 01:20 UTC, merged