ci: [WIN-NPM] remove ws19 build
Azure/azure-container-networking pull request #1844
Opened 2023-03-08 22:08 UTC by huntergregory

Unnecessary build. NPM isn't supported on Windows Server 2019

2023-03-08 23:17 UTC, huntergregory commented
/azp run

2023-03-09 16:20 UTC, rbtr approved these changes

2023-03-09 16:27 UTC, rbtr requested changes
needs Makefile fix for OS_VERSIONS (can you update the CNS manifest target also?)

2023-03-09 20:05 UTC, rbtr approved these changes

2023-04-06 19:39 UTC, vakalapa approved these changes

2023-04-11 21:34 UTC, merged