fix: [WIN-NPM] update PATH so we can use debugging tools via NPM
Azure/azure-container-networking pull request #1867
Opened 2023-03-21 20:11 UTC by huntergregory

**Reason for Change**:
Make sure NPM can still access debugging tools.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:
Currently cannot access `vfpctrl` and other tools which HNS uses to collect logs. The solution to use `vfpctrl` (which we use to view VFP endpoints), is to add `C:\Windows\System32\` to the PATH.  Adding `%CONTAINER_SANDBOX_MOUNT_POINT%\Windows\System32\` wouldn't work since `vfpctrl` is not there.

2023-03-22 17:01 UTC, vakalapa requested changes
@rbtr @matmerr  wdyt ?

2023-03-23 21:38 UTC, huntergregory commented on npm/examples/windows/azure-npm.yaml
appending with %PATH% doesn't actually append anything

2023-03-23 21:53 UTC, huntergregory commented on npm/examples/windows/azure-npm.yaml
> +              value: '%CONTAINER_SANDBOX_MOUNT_POINT%\Windows\System32\WindowsPowershell\v1.0\;C:\Windows\System32\'
appending with %PATH% doesn't actually append anything

2023-03-27 16:56 UTC, huntergregory commented on npm/examples/windows/azure-npm.yaml
> -            - name: PATH
remove our first attempt at mitigation, which is not back-compat and is incomplete (can't use vfpctrl and other tools used by HNS to collect logs)

2023-03-27 17:49 UTC, vakalapa approved these changes

2023-03-27 18:07 UTC, merged