Testing removing ssh rule in aks-engine
Azure/azure-container-networking pull request #1983
Opened 2023-05-26 23:16 UTC by pjohnst5

This is to test removing the 22 ssh nsg rule from aks-e cluster on top of Shufang's fork
https://github.com/csfmomo/aks-engine/tree/paujohns/remove-22

2023-05-30 16:04 UTC, pjohnst5 commented
/azp run

2023-05-31 16:56 UTC, matmerr approved these changes

2023-05-31 18:15 UTC, huntergregory approved these changes

2023-05-31 18:33 UTC, pjohnst5 commented
Just working with SBOM team to get that Add SBOM generator step fixed

2023-05-31 18:52 UTC, nairashu commented
I would also remove the 3389 port from AKS Engine and then bump this version. 3389 is being also reported outside of port 22.

2023-05-31 18:53 UTC, nairashu requested changes
Requesting to remove 3389 port as well when fixing this

2023-05-31 19:13 UTC, nairashu approved these changes

2023-05-31 19:14 UTC, pjohnst5 commented
/azp run

2023-06-01 18:59 UTC, pjohnst5 commented
/azp run

2023-06-05 16:43 UTC, paulyufan2 commented
/azp run

2023-06-05 19:55 UTC, paulyufan2 commented
/azp run

2023-06-05 22:52 UTC, merged