log process id instead of log name
Azure/azure-container-networking pull request #2100
Opened 2023-08-02 01:48 UTC by paulyufan2

**Reason for Change**:

This PR is to get rid of repeated "logger: azure-vnet" name. Instead, it will print the process id, such as : "pid":301

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2023-08-03 14:05 UTC, paulyufan2 commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
Hi Vipul, you can see current log as above.

2023-08-03 16:19 UTC, vipul-21 commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
`{"level":"info","ts":"2023-08-02T02:38:03.651Z","msg":"Plugin stopped","pid":0,"component":"cni-net"}`, the component will be remove as per PR#2099. So the log will be `{"level":"info","ts":"2023-08-02T02:38:03.651Z","msg":"Plugin stopped","pid":0,"}` ? If so, how would we know that which plugin stopped  ?

2023-08-03 16:25 UTC, rbtr commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
I think removing the component (#2099) is a mistake

2023-08-03 16:33 UTC, paulyufan2 commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
Hi @rbtr As Tamilmani mentioned that CNI is mostly single threaded, so adding the component in each log is not that helpful

2023-08-03 17:29 UTC, tamilmani1989 commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
we can keep component if you guys say so. but based on my debugging experince, i never looked at component in log.

@paulyufan2 the way you are getting pid is wrong. @vipul-21 each plugin will have different log file.. if azure-vnet.log, then cni plugin, if azure-vnet-ipam.log, then its ipam plugin

2023-08-03 17:33 UTC, tamilmani1989 commented on cni/log/logger.go
> +	Logger = Logger.With(zap.Int("pid", os.Getgid()))
@paulyufan2 Let's keep component for now and review back later. you can abandon this PR and create a PR for adding PID and remove logger name

2023-08-11 16:41 UTC, vipul-21 requested changes

2023-08-11 16:41 UTC, vipul-21 commented on cni/log/logger.go
> +	return Logger.Named("")
We don't need to return the Logger.Named(""). We can now just return the `Logger`. By default Logger is unnamed.

2023-08-11 17:56 UTC, vipul-21 approved these changes

2023-08-11 23:17 UTC, rbtr approved these changes

2023-08-12 03:47 UTC, merged