ci: update CNS|dropgz version
Azure/azure-container-networking pull request #2169
Opened 2023-08-22 17:19 UTC by jpayne3506

**Reason for Change**:

Container registry cleanup removed old images greater than 30d. Going forward these image versions will not be deleted.

**Issue Fixed**:

**Requirements**:

- [x] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [x] relevant PR labels added

**Notes**:

2023-08-22 19:20 UTC, rbtr requested changes

2023-08-22 19:20 UTC, rbtr commented on hack/manifests/cni-installer.yaml
> +          image: acnpublic.azurecr.io/cni-dropgz:v0.0.10
can you update these `acnpublic` refs to be `mcr` instead?

2023-08-23 16:57 UTC, rbtr submitted a review, later dismissed
lgtm

2023-08-23 20:47 UTC, paulyufan2 approved these changes

2023-08-24 17:07 UTC, vipul-21 approved these changes

2023-08-24 17:55 UTC, vakalapa approved these changes

2023-08-24 17:55 UTC, merged