change total IPs and add secondary IP metric
Azure/azure-container-networking pull request #2172
Opened 2023-08-23 17:58 UTC by rbtr

**Reason for Change**:

Updates the Total IPs metrics to include the NC Primary IP in the total. Adds a Secondary IPs metric which holds the value that the Total IPs previously held: NC Secondary IPs known to CNS which could be used by Pods.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2023-08-25 16:11 UTC, nairashu commented on cns/ipampool/metrics.go
> +			Help:        "NC Primary IP count (unassignable).",
As this help is going to be a tooltip and it is counting primary IPs across the cluster I would describe it as:
```suggestion
			Help:        "Cluster Primary IP count (unassignable to pods).",
```

2023-08-25 16:16 UTC, nairashu commented on cns/ipampool/metrics.go
> +			Help:        "NC Secondary IP count (assignable).",
```suggestion
			Help:        "Cluster Secondary IP count (assignable to pods).",
```

2023-08-25 16:25 UTC, nairashu approved these changes
Suggested minor changes to the naming patterns

2023-08-25 18:05 UTC, nairashu submitted a review, later dismissed

2023-08-25 22:32 UTC, neaggarwMS commented on cns/ipampool/metrics.go
> +			Help:        "Node NC Primary IP count (reserved not usable by Pods).",
I would say "Primary IP Count that is reserved from PodSubnet CIDR, it is reserved to SNAT DNS traffic

2023-08-25 22:32 UTC, neaggarwMS commented on cns/ipampool/metrics.go
> +			Help:        "Node NC Primary IP count (reserved not usable by Pods).",
Cx was confusing this with Node Primary ip from Node CIDR

2023-08-25 22:34 UTC, neaggarwMS requested changes
added feedback

2023-08-28 19:33 UTC, neaggarwMS approved these changes

2023-08-28 19:40 UTC, nairashu approved these changes

2023-08-28 19:45 UTC, merged