ci: v4overlay conformance test cases
Azure/azure-container-networking pull request #2274
Opened 2023-10-03 21:14 UTC by paulyufan2

**Reason for Change**:

This is to restruct v4overlay conformance tests

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2023-10-03 21:59 UTC, jpayne3506 requested changes

2023-10-03 21:59 UTC, jpayne3506 commented on .pipelines/singletenancy/azure-cni-overlay/azure-cni-overlay-e2e-job-template.yaml
> +          portforward: true
We can add `hostport: true` to the windows tests as we are only seeing issues with dualstack.

2023-10-04 19:00 UTC, jpayne3506 approved these changes

2023-10-04 20:07 UTC, vipul-21 approved these changes

2023-10-05 01:13 UTC, jpayne3506 approved these changes

2023-10-05 01:27 UTC, vipul-21 approved these changes

2023-10-05 03:07 UTC, merged