[CNI] Migrate zap logger for acn ipam package
Azure/azure-container-networking pull request #2299
Opened 2023-10-17 18:48 UTC by paulyufan2

**Reason for Change**:

This PR is to migrate zap logger for ACN ipam package

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2023-10-17 19:24 UTC, behzad-mir requested changes

2023-10-17 19:24 UTC, behzad-mir commented on ipam/ipv6Ipam.go
> +		logger.Error("[ipam] Failed retrieve Kubernetes IP's from subnet", zap.Error(err))
you can remover [ipam]

2023-10-27 18:35 UTC, vipul-21 requested changes

2023-10-27 18:35 UTC, vipul-21 commented on ipam/azure.go
> +		logger.Info("Failed intializing http client")
logger.Error ?

2023-10-27 18:35 UTC, vipul-21 commented on ipam/azure.go
> +		logger.Info("http return error code for wireserver call", zap.Any("response", resp))
logger.Error ?

2023-10-27 19:50 UTC, behzad-mir commented on ipam/ipv6Ipam.go
> +		logger.Error("[ipam] Failed retrieve Kubernetes IP's from subnet", zap.Error(err))
The [ipam] is still there

2023-10-27 21:17 UTC, vipul-21 approved these changes

2023-10-27 21:38 UTC, behzad-mir approved these changes

2023-10-28 04:38 UTC, merged