use renamewithnetsh for nc rename
Azure/azure-container-networking pull request #2392
Opened 2023-11-15 19:07 UTC by dejandundjerski

**Reason for Change**:
Use netsh when creating NC instead of powershell to improve overall create time.

2023-11-15 19:42 UTC, tamilmani1989 commented
/azp run

2023-11-15 20:02 UTC, tamilmani1989 approved these changes

2023-11-16 16:51 UTC, ramiro-gamarra requested changes
No change needed per se, but need to clarify what the impact of this change is since it will be default for all CNS users.

2023-11-20 17:42 UTC, ramiro-gamarra requested changes

2023-11-20 17:42 UTC, ramiro-gamarra commented on cns/networkcontainers/networkcontainers_windows.go
> +		fmt.Sprintf("%t", configuration.CnsConfig.EnableRenameWithNetSh),
Should not be consumed from a global. It should be passed as a parameter (like `setWeakHost`)

2023-11-20 17:42 UTC, ramiro-gamarra commented on cns/configuration/configuration.go
> +var CnsConfig CNSConfig
no globals please.

2023-12-28 00:01 UTC, closed without merging