CI: Setup Cilium with Hubble Enabled nightly run
Azure/azure-container-networking pull request #2471
Opened 2024-01-04 21:01 UTC by MikeZappa87

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2024-01-08 19:52 UTC, matmerr approved these changes

2024-01-10 23:50 UTC, MikeZappa87 commented
@matmerr take a look when you get a chance. Make sure I covered everything.

2024-01-10 23:53 UTC, MikeZappa87 commented on test/integration/manifests/cilium/v1.14.4/cilium-config/cilium-config-hubble.yaml
> +  hubble-metrics: flow:sourceContext=pod;destinationContext=pod tcp:sourceContext=pod;destinationContext=pod
@matmerr I think you mentioned we needed additional labels for some of the metrics.

2024-01-16 18:04 UTC, matmerr requested changes
minor things, other than that looks good 🙌

2024-01-16 18:04 UTC, matmerr commented on test/integration/networkobservability/hubble_test.go
> +}
given this init is var instantiation, we could move this to the var() block where it's declared and avoid the additional init

```suggestion

var (
    flow       = []string{"source", "destination"}
    hubbleKeys = map[string][]string{
		    "hubble_flows_processed_total": flow,
             ...
    }
)
```

2024-01-16 19:36 UTC, closed without merging