Adding UTs for addDNSServers
Azure/azure-container-networking pull request #2507
Opened 2024-01-15 10:16 UTC by anubhabMajumdar

**Reason for Change**:
Adding UTs for `addDNSServers` function. 

**Issue Fixed**:

**Requirements**:
Check in after https://github.com/Azure/azure-container-networking/pull/2506 is checked in.

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [x] adds unit tests
- [x] relevant PR labels added

**Notes**:

2024-01-16 22:14 UTC, rbtr requested changes
I don't see the need for these to be Ginkgo, can you make them plain Go tests pls

2024-01-17 01:45 UTC, jpayne3506 commented on network/network_linux_test.go
> +		{
Do we know of any commonly used cmd(s) that should fail, so we can have some negative tests?

2024-01-26 01:50 UTC, jpayne3506 approved these changes

2024-02-01 17:42 UTC, vipul-21 commented on network/network_linux_test.go
> +func TestAddDNSServersWithErr(t *testing.T) {
This checks for empty dnsServers length case right ? Ifo so, the result of the error is `nil` so not sure if `TestAddDNSServersWithErr` make sense as we don't expect an error ?

2024-08-20 20:23 UTC, timraymond commented on network/network_linux_test.go
> +		t.Log("Running: ", tc.desc, " for ", tc.osversion)
Please use `t.Run` for this so we can get the benefits of subtests. The name of the subtest can just be `tc.desc`, or you can concatenate the `tc.osversion` as well if you want.

2024-08-20 20:23 UTC, timraymond commented on network/network_linux_test.go
> +			t.Errorf("Expected error: %v, got: %v", tc.err, err)
Typically I make these Fatal, on the grounds that if an error occurred, it's usually nonsensical to try to compare anything about the results of the thing I was trying to do when the error occurred. You just end up with extra output in the test that obscures what the actual root cause of the test failure was.

2024-09-05 19:09 UTC, timraymond commented
@anubhabMajumdar The required PR in the description has merged btw. Stalebot is awake.

2024-11-01 00:01 UTC, closed without merging