Revert "Enable CNS swiftv2 path for SF/Standalone scenario to program secondary nics"
Azure/azure-container-networking pull request #2608
Opened 2024-02-26 22:58 UTC by kmurudi

Reverts Azure/azure-container-networking#2444 due to blocking stateless CNI (structs in restserver moved to api.go)

2024-02-28 01:03 UTC, nddq commented
can we ignore the linter errors + e2e pipeline for this to merge? @rbtr

2024-03-01 20:03 UTC, nddq approved these changes

2024-03-01 21:29 UTC, behzad-mir requested changes

2024-03-01 21:29 UTC, behzad-mir commented on cns/restserver/restserver.go
> +type HTTPRestServiceData struct { //nolint:musttag // not tagging struct for revert-PR
Can you also add a TODO as @tamilmani1989 suggested to the new //nolint?

2024-03-01 21:35 UTC, jpayne3506 submitted a review, later dismissed

2024-03-01 21:55 UTC, behzad-mir approved these changes

2024-03-01 22:38 UTC, nddq approved these changes

2024-03-04 10:09 UTC, merged