L1VH CNI Code changes
Azure/azure-container-networking pull request #2616
Opened 2024-02-29 18:10 UTC by paulyufan2

**Reason for Change**:

This implementation is to support swiftv2 L1VH CNI feature:
CNI receives goal state from CNS and create linux/windows pod on Windows VM/Node in swiftv2 L1VH path;
The container pod is using secondary interface with its mac address and NIC type(Delegated NIC or Accelnet) to be created;
We support up to 8 pods to be created by using different interfaces along with different hnsNetwork; CNI supports hnsNetwork creation(when pod is added to the VM) and deletion(when pod is removed from VM) to prevent leakage;

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2024-03-01 00:51 UTC, jpayne3506 commented on cni/network/network_windows.go
> +
```suggestion
	// in multitenancy case, the network name will be in the state file or can be built from cnsResponse
	if len(strings.TrimSpace(netNs)) == 0 {
		return "", fmt.Errorf("NetNs cannot be empty")
	}

	// if it's swiftv2 secondaryInterfaceNIC, then use "azure-macAddres" format networkName
	// networkName will look like ~ azure-01:23:ab:f4:ac:95
	if ipamAddResult != nil && hasSecondaryInterfaceNIC {
		swiftv2NetworkName := "azure-" + ipamAddResult.secondaryInterfacesInfo[0].MacAddress.String()
		logger.Info("swiftv2 network name is", zap.String("swiftv2NetworkName", swiftv2NetworkName))
		return swiftv2NetworkName, nil
	}

```

2024-03-01 00:51 UTC, jpayne3506 commented on network/endpoint_windows.go
> +	for i, ipconfig := range epInfo.IPAddresses {
Shouldn't we use ep.IPAddresses instead?

2024-03-01 00:51 UTC, jpayne3506 commented on network/network.go
> +				if interfaceInfo := epID.SecondaryInterfaces[endpointID]; interfaceInfo != nil {
what does epID stand for or represent?

2024-03-01 16:46 UTC, paulyufan2 commented on cni/network/network.go
> +		interfaceInfo = ipamAddResult.secondaryInterfacesInfo[0]
For every call from DNC, we only retrieve one second interface from CNS, so first element of secondaryInterfacesInfo will be always our secondary interface info

2024-03-01 16:47 UTC, paulyufan2 commented on cni/network/invoker_cns_test.go
> +									NICType:    cns.DelegatedVMNIC,
Currently, they call IB NIC as backendNIC from CNS

2024-03-01 16:48 UTC, paulyufan2 commented on cni/network/network.go
> +			default:
in CNS, we defined these NIC types as DeletegatedNIC and BackendNIC; we will also have Accelnet NIC type

2024-03-01 16:49 UTC, paulyufan2 commented on network/network.go
> +				if interfaceInfo := epID.SecondaryInterfaces[endpointID]; interfaceInfo != nil {
this should be endpoint, renamed it...

2024-03-01 18:43 UTC, jpayne3506 commented
/azp run Azure Container Networking PR

2024-03-01 18:44 UTC, jpayne3506 commented
/azp run Azure Container Networking PR

2024-03-01 18:57 UTC, rbtr commented
we don't use integration branches, why is this not targeting master?

2024-03-01 20:11 UTC, jpayne3506 commented on cni/network/invoker_cns_test.go
> +									NICType:    cns.DelegatedVMNIC,
Lets pull these UT's out for its own PR. Our code change here will not call it.

2024-03-01 20:17 UTC, jpayne3506 commented on cni/network/network.go
> +		interfaceInfo = ipamAddResult.secondaryInterfacesInfo[0]
@jaer-tsun, can you provide some additional context as well? I want to fully understand what `secondaryInterfacesInfo` will be used for and is currently being used for.

2024-03-01 21:41 UTC, jpayne3506 commented
We can not merge this code to master until `github.com/Microsoft/hcsshim v0.12.0-rc.2` is out of release candidate status. We want to be able to still work, test, and retain code reviews for this work.

2024-03-05 00:36 UTC, tamilmani1989 requested changes

2024-03-05 00:36 UTC, tamilmani1989 commented on network/endpoint_windows.go
> +	}
iterate epinfo and create hns endpoint for each epInfo

2024-03-05 00:36 UTC, tamilmani1989 commented on network/endpoint.go
> +	Endpoint                 endpoint
its not required to add whole endpoint structure.. it will be duplicating fields here

2024-03-05 00:36 UTC, tamilmani1989 commented on network/endpoint_windows.go
> +	if epInfo.NICType != cns.InfraNIC {
lets remove infranic check

2024-03-05 00:36 UTC, tamilmani1989 commented on network/endpoint_windows.go
> +	ep.SecondaryInterfaces[ep.Id] = &InterfaceInfo{
key should be epInfo.IfName

2024-03-05 23:11 UTC, jaer-tsun commented on cni/network/invoker_cns.go
> +			// Add secondary interface info from podIPInfo to ipamAddResult
split BackendNIC into separate case

2024-03-05 23:12 UTC, jaer-tsun commented on cni/network/network.go
> +		interfaceInfo = ipamAddResult.secondaryInterfacesInfo[0]
looks like there should be a check for L1VH type before setting interfaceInfo as 1st element from secondaryInterfacesInfo

2024-03-05 23:53 UTC, jaer-tsun commented on cni/network/network.go
> +func (plugin *NetPlugin) findInterfaceByMAC(macAddress string) string {
there's also a func that takes the hardware mac in netio called GetNetworkInterfaceByMac

2024-03-06 00:10 UTC, jaer-tsun commented on cni/network/network.go
> +		if ipamAddResult != nil && len(ipamAddResult.secondaryInterfacesInfo) > 0 {
where does the interface usage map get cleaned up?

2024-03-06 00:11 UTC, jaer-tsun commented on cni/network/network_windows.go
> +	hasSecondaryInterfaceNIC := false
hasSecondaryInterfaceNIC := hasSecondaryInterface(*ipamAddResult)

2024-03-06 00:13 UTC, jaer-tsun commented on cni/network/network_windows.go
> +	if ipamAddResult != nil && hasSecondaryInterfaceNIC {
maybe add the nil check in hasSecondaryInterface func to return false when nil

2024-03-06 00:15 UTC, jaer-tsun commented on network/endpoint_windows.go
> +	macAddress := strings.Join(strings.Split(epInfo.MacAddress.String(), ":"), "-")
does replacing : with - work too?

2024-04-03 00:01 UTC, closed without merging