Fix condition to use default value in case parameter is not set
Azure/azure-container-networking pull request #2880
Opened 2024-07-25 23:06 UTC by smittal22

**Reason for Change**:
[PR](https://github.com/Azure/azure-container-networking/pull/1768) introduced a change where if the `MellanoxMonitorIntervalSecs` is not passed in we should use the default value, however the condition was faulty and in case of default 0 value, we are not defaulting to 30 secs default value.

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] relevant PR labels added

**Notes**:

2024-07-25 23:30 UTC, ramiro-gamarra requested changes
if `inervalSecs` is 0, the default monitoring interval needs to be used

2024-07-30 19:30 UTC, rbtr commented
@smittal22 this PR shows no changes now, which doesn't seem right

2024-07-30 20:29 UTC, smittal22 commented
> @smittal22 this PR shows no changes now, which doesn't seem right

@rbtr Yeah, I reverted it. Will work on it later. Might even close this out.

2024-07-30 20:40 UTC, timraymond commented
@smittal22 No need to push a revert commit on something that hasn't been merged. You can just leave it.

2024-08-22 00:01 UTC, closed without merging