chore: Specify CI build pool name
Azure/azure-container-networking pull request #841
Opened 2021-03-31 19:48 UTC by matmerr

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2021-04-05 17:21 UTC, matmerr commented
/azp run

2021-04-05 17:29 UTC, matmerr commented
/azp run

2021-04-05 17:32 UTC, matmerr commented
/azp run

2021-04-05 20:09 UTC, vakalapa submitted a review, later dismissed
Build pipeline changes look good. You will need to check others for CNM test

2021-04-13 15:37 UTC, tamilmani1989 requested changes

2021-04-13 15:37 UTC, tamilmani1989 commented on cni/network/network_test.go
> +		}*/
why this is commented?

2021-04-13 15:37 UTC, tamilmani1989 commented on cni/network/network_test.go
> +	//plugin.Add(args)
same as above

2021-04-13 15:37 UTC, tamilmani1989 commented on network/network_linux.go
> +			cmd = fmt.Sprintf("systemd-resolve --interface=%s --set-domain=%s", ifName, extIf.DNSInfo.Suffix)
make it separate 
if extIf.DNSInfo.Suffix != "" {
}

2021-04-13 15:37 UTC, tamilmani1989 commented on cnm/network/network_test.go
> +
is this still needed?

2021-04-13 15:59 UTC, tamilmani1989 submitted a review, later dismissed
lgtm

2021-04-13 16:00 UTC, tamilmani1989 approved these changes

2021-04-13 18:00 UTC, merged