[CNI] Specify CNSClient HTTPClient timeout
Azure/azure-container-networking pull request #862
Opened 2021-04-30 20:20 UTC by matmerr

**Reason for Change**:

**Issue Fixed**:

No timeout specified in CNI, so when CNS is locked and won't respond, this issue gets propagated down to CNI being locked waiting for a response from CNS.

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2021-05-03 17:23 UTC, matmerr commented on cni/network/network.go
> +	defaultRequestTimeout = 5 * time.Second
update request timeout to 15 seconds

2021-05-03 17:26 UTC, neaggarwMS requested changes

2021-05-03 17:26 UTC, neaggarwMS commented on cni/network/network.go
> +	defaultRequestTimeout = 5 * time.Second
Can you change it to 15 seconds

2021-05-05 18:05 UTC, thatmattlong approved these changes

2021-05-05 23:57 UTC, neaggarwMS approved these changes

2021-05-06 00:01 UTC, merged