[NPM] NPM Debug CLI
Azure/azure-container-networking pull request #971
Opened 2021-08-12 18:13 UTC by nddq

This PR contains the code for the NPM Debug CLI that interacts with the data plane parser + converter and traffic analyzer.

To use this CLI, simply build the NPM binaries and then execute it with the flag debug. i.e /usr/bin/azure-npm debug.

2021-08-13 00:20 UTC, huntergregory requested changes
Looks good Quang. Loved the demo you showed me earlier. Couple things:
1. You have some duplicate logic in your 3 cobra commands (parseIPtable, getTuples, convertIPtable) where you get the result and error from a function and then print those two out. Can you condense this? 
Example: 
```
if npmCacheF == "" && iptableSaveF == "" {
	ipTableRulesRes, err := c.GetJSONRulesFromIptables(iptableName)
	if err != nil {
		fmt.Printf("%+v\n", err)
	}
	fmt.Printf("%s\n", ipTableRulesRes)
} else {
	ipTableRulesRes, err := c.GetJSONRulesFromIptableFile(iptableName, npmCacheF, iptableSaveF)
	if err != nil {
		fmt.Printf("%+v\n", err)
	}
	fmt.Printf("%s\n", ipTableRulesRes)
}
```
Write this as
```
var result TYPE
var err error
if () { 
	result, err := c.Get(name)
} else {
	result, err := c.GetFromFile(name, cacheFile, saveF)
}
if err != nil {
	// print error
}
// print result
```
2. Do you have the team's go linter? You have some weird formatting like a new line before the end of a function sometimes, which GitHub doesn't like.
3. Could you skip the else bracket in plugin/main.go? Just say `return` after the if statement? Seems a little cleaner. 

Then just a couple questions for my own understanding:
1. When would there be more than os arg in main.go, and why do you skip the rest of the function when this is the case?
2. Why are we switching from klog to log? Also, did you mean to delete the "Start NPM version" log line?

2021-08-13 00:57 UTC, rbtr commented
@huntergregory
> Write this as
> 
> ```
> var result TYPE
> var err error
> if () { 
> 	result, err := c.Get(name)
> } else {
> 	result, err := c.GetFromFile(name, cacheFile, saveF)
> }
> if err != nil {
> 	// print error
> }
> // print result
> ```

Whenever I see variable declarations moving further from their use, I get suspicious (that something more significant is wrong with the flow)... maybe once the branches of the if/else approach the size of the dedup or get over a handful of lines each, I would argue against this.

@nddq 
Since these cmds are in a `RunE`, you don't need to print errs here, you can just return them and let the root invocation log and exit. And I'm not sure of this, but I think all of `GetNetworkTupleFile` func args need to be valid, so should we `||` instead of `&&`?

2021-08-13 17:26 UTC, nddq commented
> 1. Do you have the team's go linter? You have some weird formatting like a new line before the end of a function sometimes, which GitHub doesn't like.
> 2. Could you skip the else bracket in plugin/main.go? Just say `return` after the if statement? Seems a little cleaner.
> 
> Then just a couple questions for my own understanding:
> 
> 1. When would there be more than 1 os arg in main.go, and why do you skip the rest of the function when this is the case?
> 2. Why are we switching from klog to log? Also, did you mean to delete the "Start NPM version" log line?

1. Can you point out a case of weird formatting for me because I don't seem to find any. I run the golangci-lint every time I planned to commit the code so this should not be an issue.
2. Did you mean the else bracket after `if len(os.Args) > 1`? This is actually the entry point for NPM :) 
3. To loop back to my previous answer, I want to start the CLI only when there is a debug command right after calling the binaries, otherwise, it would start NPM itself. That's why I have a check for the os.Args.
4. This is my mistake, I some how had the old main.go file. I fixed that in my most recent commit!

2021-08-13 17:27 UTC, nddq commented
@rbtr 
> Since these cmds are in a `RunE`, you don't need to print errs here, you can just return them and let the root invocation log and exit. And I'm not sure of this, but I think all of `GetNetworkTupleFile` func args need to be valid, so should we `||` instead of `&&`?

Yep you are correct, I will fix that.

2021-08-13 21:50 UTC, matmerr requested changes
Mostly ux changes 👍

2021-08-13 21:50 UTC, matmerr commented on npm/debugTools/cmd/debugCmd.go
> +	debugCmd.PersistentFlags().StringP("table", "t", "", "Set table name (default to filter)")
If we add another cmd it might not require these flags, potentially reduce scope

2021-08-13 23:41 UTC, rbtr commented on npm/debugTools/cmd/root.go
> +	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.cli.yaml)")
it is kind of a pain to set env vars on the fly if you want to test different configs though

2021-08-14 00:23 UTC, matmerr commented on npm/debugTools/cmd/root.go
> +	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.cli.yaml)")
Perhaps, but some of the options that are being added here are on-disk targets, (npm cache file path, iptables-save file path) and if I need to test those on the fly I'll just set the npmF/iptF flag in the line for the cmd that needs it

The rest of options like src/dst/table are command specific and probably won't be in a config

2021-08-17 22:55 UTC, matmerr approved these changes
🚀

2021-08-17 23:29 UTC, merged