chore: Add mock prefix so generated code is not counted against coverage
Azure/azure-container-networking pull request #983
Opened 2021-08-27 22:02 UTC by matmerr

**Reason for Change**:

**Issue Fixed**:

**Requirements**:

- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests

**Notes**:

2021-09-01 23:32 UTC, neaggarwMS requested changes

2021-09-01 23:32 UTC, neaggarwMS commented on Makefile
> +	@$(eval CVPKG=`go list ./... | grep -v mock | tr '\n' ','`)
isnt the package named "mockclients"

2021-09-13 16:54 UTC, neaggarwMS approved these changes

2021-09-21 03:54 UTC, tamilmani1989 approved these changes

2021-09-21 16:26 UTC, merged